name = "BallSim"
uuid = "a1b2c3d4-e5f6-4789-0123-456789abcdef"
version = "0.0.1"
authors = ["Ben Brandt <benbrandt14@gmail.com>"]

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
ProgressMeter = "92933f4c-e287-5a05-a399-4b561866384a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[compat]
CairoMakie = "0.12"
GLMakie = "0.10"
HDF5 = "0.17"
ProgressMeter = "1.0"
StaticArrays = "1.9"
StructArrays = "0.6"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
