name = "BallSim"
uuid = "a1b2c3d4-e5f6-4789-0123-456789abcdef"
authors = ["Your Name <you@example.com>"]
version = "0.1.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CairoMakie = "0.12"
GLMakie = "0.10"
HDF5 = "0.17"
ProgressMeter = "1.0"
StaticArrays = "1.9"
StructArrays = "0.6"
julia = "1.10"
LinearAlgebra = "1.0"
Printf = "1.0"
Dates = "1.0"
Random = "1.0"
Statistics = "1.0"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]