[deps]
BallSim = "a1b2c3d4-e5f6-4789-0123-456789abcdef"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Stipple = "4acbeb90-81a0-11ea-1966-bdaff8155998"
StippleUI = "a3c5d34a-b254-4859-a8fa-b86abb7e84a3"
