name = "BallSimTools"
uuid = "1e86a9f4-2c71-4a57-9d22-1b8f1c8a1e12"
authors = ["Ben Brandt <benbrandt14@gmail.com>"]
version = "0.1.0"

[deps]
BallSim = "a1b2c3d4-e5f6-4789-0123-456789abcdef"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"

[compat]
JET = "0.9"
JuliaFormatter = "2.2"
julia = "1.10"
