[deps]
BallSim = "a1b2c3d4-e5f6-4789-0123-456789abcdef"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Documenter = "1"
StaticArrays = "1.9"
