[deps]
BallSim = "a1b2c3d4-e5f6-4789-0123-456789abcdef"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TikzPictures = "37f6aa50-8035-52d0-81c2-5a1d08754b2d"

[compat]
Documenter = "1"
StaticArrays = "1.9"
